### ISSUE TITLE
Line spacing problem

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/content-page#1]
Hi @thomasjbradley!

I've made the spacing and alignments as close as I can get them for the smallest screen size; however, I'm running into an issue where the citation and all the text beyond that are slightly lower than the example given. I've played some with where I place padding in the document, but cannot get it to render with better than 17% accuracy. (My assumption is that the way your fractional padding is distributed is based on relative line height of the item to which padding is applied, but even so, I haven't been able to guess-and-check my way into a pass from Markbot.)

Note: I'm not done with the assignment, so ignore the other errors currently occurring, if they are still there by the time you see this. (Here's hoping you take an actual break over the holidays, and don't see this 'til the new year!)

<img width="838" alt="screen shot 2018-12-22 at 10 12 03 pm" src="https://user-images.githubusercontent.com/19557909/50380490-ba977700-0636-11e9-9c9d-dfeed8c564c5.png">

**Comment by thomasjbradley** [comment]
I looked through your code & my solution and they’re really close. The only difference I can see, that may be causing it, is that my `micro` font-size class is on `<footer>` not on the `<cite>`.

Try that out and see if it works.

**Comment by MacKenzieRose** [comment]
@thomasjbradley It brings it close enough to pass! Thank you :)
